__author__ = 'Arin'
import os

class CONST(object):
    jets = 0
    sharks = 1
    bruiser_max_hp = 15
    bruiser_min_hp = 12
    bruiser_max_strength = 12
    bruiser_min_strength = 9
    bruiser_max_finesse = 9
    bruiser_min_finesse = 6
    bruiser_max_style = 6
    bruiser_min_style = 3
    bruiser_max_wit = 3
    bruiser_min_wit = 1
    greaser_max_hp = 12
    greaser_min_hp = 9
    greaser_max_strength = 3
    greaser_min_strength = 1
    greaser_max_finesse = 15
    greaser_min_finesse = 12
    greaser_max_style = 6
    greaser_min_style = 3
    greaser_max_wit = 9
    greaser_min_wit = 6
    squabbler_max_hp = 9
    squabbler_min_hp = 6
    squabbler_max_strength = 6
    squabbler_min_strength = 3
    squabbler_max_finesse = 3
    squabbler_min_finesse = 1
    squabbler_max_style = 12
    squabbler_min_style = 9
    squabbler_max_wit = 15
    squabbler_min_wit = 12
    sh_sq_im_path = os.path.join("pixel_art","s_sq.png")
    jt_sq_im_path = os.path.join("pixel_art","j_sq.png")
    sh_br_im_path = os.path.join("pixel_art","s_br.png")
    jt_br_im_path = os.path.join("pixel_art","j_br.png")
    sh_gr_im_path = os.path.join("pixel_art","s_gr.png")
    jt_gr_im_path = os.path.join("pixel_art","j_gr.png")
    sh_sq_im_pathb = os.path.join("pixel_art","s_sq_bkg.png")
    jt_sq_im_pathb = os.path.join("pixel_art","j_sq_bkg.png")
    sh_br_im_pathb = os.path.join("pixel_art","s_br_bkg.png")
    jt_br_im_pathb = os.path.join("pixel_art","j_br_bkg.png")
    sh_gr_im_pathb = os.path.join("pixel_art","s_gr_bkg.png")
    jt_gr_im_pathb = os.path.join("pixel_art","j_gr_bkg.png")
    rd_path = os.path.join("pixel_art","rd.png")
    gs_path = os.path.join("pixel_art","gs.png")
    cr_path = os.path.join("pixel_art","cr.png")
    sp_path = os.path.join("pixel_art","rt.png")
    tcr_path = os.path.join("pixel_art","tcr.png")
    wall_path = os.path.join("pixel_art","wall.png")
    br_at = os.path.join("sfx","woosh.wav")
    gr_at = os.path.join("sfx","switchblade.wav")
    sq_at = os.path.join("sfx","hey.wav")
    move_sfx = os.path.join("sfx","steps.wav")
    conf = os.path.join("sfx","confirm.wav")
    bruiser_movement = 4
    squabbler_movement = 5
    greaser_movement = 6
    cncl = os.path.join("sfx","cancel.wav")
    turn_sound = os.path.join("sfx","congo.wav")
    none= os.path.join("pixel_art","empty.png")
    select=0
    move=1
    menu=2
    attack=3
    special = 4
